### ISSUE TITLE
How do I get the server link for the operation in blackeye latest version. 

### ISSUE THREAD

**Issue by UNKNOWNsecret1** [Git-Ankitraj/blackeye-im#1]

**Comment by UNKNOWNsecret1** [comment]
![image](https://user-images.githubusercontent.com/39586701/106406061-6d527a00-6438-11eb-8502-ad8799d293ca.png)
since it looks like this

**Comment by Grotti200** [comment]
Same for me...

**Comment by Git-Ankitraj** [comment]
Isn't the ngrok link appears?

**Comment by Git-Ankitraj** [comment]
There must be some problem with ngrok. Clone the repo again and see if it's working.

**Comment by Grotti200** [comment]
<img width="1202" alt="Screenshot 2021-02-15 at 00 06 59" src="https://user-images.githubusercontent.com/54181093/107890437-cb478d00-6f21-11eb-983e-bbb766285c69.png">
Still not working.

**Comment by Grotti200** [comment]
It only works on linux, right?

**Comment by Git-Ankitraj** [comment]
I haven't tested it on any other machines except linux (Ubuntu 20.04, Debian, kali 2020 and Garuda linux) and it's working quite better. I think you are on Mac, right?

**Comment by Git-Ankitraj** [comment]
> ![image](https://user-images.githubusercontent.com/39586701/106406061-6d527a00-6438-11eb-8502-ad8799d293ca.png)
> since it looks like this

Are you using it on Termux?

**Comment by Git-Ankitraj** [comment]
> It only works on Linux, right?

Yeah, The scripts are according to Linux. But you can also run it on macOS by manually installing the requirements.

**Comment by sixseven49** [comment]
![Screenshot 2021-03-31 at 11 08 40](https://user-images.githubusercontent.com/13555311/113128189-73cf5900-9211-11eb-8598-9aa047efa4dc.png)
Im using Kali L<inux and its still not working

**Comment by topgas** [comment]
it work for me good , but why when i send the link to the victim(example) it dosent go online ? what should i do ? and thank for the time

**Comment by mojaas** [comment]
> it work for me good , but why when i send the link to the victim(example) it dosent go online ? what should i do ? and thank for the time

are you using linux 2021?

**Comment by Git-Ankitraj** [comment]
It's working.
![Screenshot_2021-04-21-13-30-31-676_com termux](https://user-images.githubusercontent.com/62335141/115522229-8d603f80-a2a9-11eb-9c4e-cf5da39c9b39.jpg)
