### ISSUE TITLE
Nothing happens after opening link.

### ISSUE THREAD

**Issue by AluminumToast** [Git-Ankitraj/blackeye-im#14]
I am using Kali Linux on wsl
when i open the ngrok link its stuck on
[*] Waiting victim open the link ...
Tried on MS Edge, Brave, Chrome
![image](https://user-images.githubusercontent.com/56157308/121347255-ef602b80-c961-11eb-825a-46f86b9dbf55.png)

**Comment by AluminumToast** [comment]
nvm sorry i fixed it

**Comment by BLACKHAT11121** [comment]
how
