### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by vempire70** [Git-Ankitraj/blackeye-im#4]
tunnel not found 😒

**Comment by mojaas** [comment]
Samw

**Comment by mojaas** [comment]
Same

**Comment by Git-Ankitraj** [comment]
Bruhh! Please specify the distro you are using, it's not the problem with the script. On some Linux distros, the ngrok link works fine 
 on localhost whereas it says "tunnel not found" when you try to open the link on other devices. This is the problem with ngrok tunneling.

**Comment by mojaas** [comment]
How can i specify it? Do u have some videos on yt?

**Comment by mojaas** [comment]
> Bruhh! Please specify the distro you are using, it's not the problem with the script. On some Linux distros, the ngrok link works fine
> on localhost whereas it says "tunnel not found" when you try to open the link on other devices. This is the problem with ngrok tunneling.

Im using kali linux . I just installed it for this black eye. And the first thing i. Do is type you command and boom. It generates link but others can open it.  Do i need to configure something else ? It work with the other version of black eye. The one with the ngrok in it. I just open ./ngrok http 80 at the same time and type localhost:4040/ and open link then copy. The link now displays details for the fake page. But now i can used it again. Pleased help me this. Ill folllow your steps. Just do it raw like a newly install kali linux. So i can follow every thing and not miss any installed and configs. Thank you

**Comment by Git-Ankitraj** [comment]
> > Bruhh! Please specify the distro you are using, it's not the problem with the script. On some Linux distros, the ngrok link works fine
> > on localhost whereas it says "tunnel not found" when you try to open the link on other devices. This is the problem with ngrok tunneling.
> 
> Im using kali linux . I just installed it for this black eye. And the first thing i. Do is type you command and boom. It generates link but others can open it. Do i need to configure something else ? It work with the other version of black eye. The one with the ngrok in it. I just open ./ngrok http 80 at the same time and type localhost:4040/ and open link then copy. The link now displays details for the fake page. But now i can used it again. Pleased help me this. Ill folllow your steps. Just do it raw like a newly install kali linux. So i can follow every thing and not miss any installed and configs. Thank you

I am not getting any issue over here, it's working fine.
![Screenshot_2021-04-21-13-30-31-676_com termux](https://user-images.githubusercontent.com/62335141/115522561-d87a5280-a2a9-11eb-90cc-8c7ea84bcad3.jpg)
